Update git hooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Fail on first line that fails.
+set -e
+
 # Check if this is the initial commit
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -9,33 +12,38 @@ else
 fi
 
 # Use git diff-index to check for whitespace errors
-if ! git diff-index --check --cached $against
+if ! git diff-index --check --cached $against -- ':!*.js.snap' .
 then
     echo "Aborting commit due to whitespace errors."
     exit 1
-else
-    # Fail on first line that fails.
-    set -e
+fi
 
-    NEW_FILES=$(git --no-pager diff --name-only --cached)
-    JS_FILES=$(echo "$NEW_FILES" | { grep client/js || true; })
-    SASS_FILES=$(echo "$NEW_FILES" | { grep client/sass || true; })
+# Only keep staged files that are added (A), copied (C) or modified (M).
+STAGED=$(git --no-pager diff --name-only --cached --diff-filter=ACM)
+# Files which are only partly staged (eg. git add --patch).
+PATCH_STAGED=$(git --no-pager diff --name-only --diff-filter=ACM $STAGED)
+# Files which are fully staged.
+FULLY_STAGED=$(comm -23 <(echo "$STAGED") <(echo "$PATCH_STAGED"))
 
-    if [ -n "$JS_FILES" ];
-    then
-        npm run linter:js -s -- $JS_FILES
-    fi
+JS_STAGED=$(grep .js$ <<< "$STAGED" || true)
+JS_FULLY_STAGED=$(grep .js$ <<< "$FULLY_STAGED" || true)
+SCSS_STAGED=$(grep .scss$ <<< "$STAGED" || true)
+SCSS_FULLY_STAGED=$(grep .scss$ <<< "$FULLY_STAGED" || true)
+MD_STAGED=$(grep .md$ <<< "$STAGED" || true)
+MD_FULLY_STAGED=$(grep .md$ <<< "$FULLY_STAGED" || true)
+SNAPSHOT_STAGED=$(grep .snap$ <<< "$STAGED" || true)
 
-    if [ -n "$SCSS_FILES" ];
-    then
-        npm run linter:sass -s -- $SCSS_FILES
-    fi
+if [ -n "$JS_STAGED" ];
+then
+    npm run linter:js -s -- $JS_STAGED
+fi
 
-    # To test if there are changes to Sass files as well (not useful at the moment):
-    # if [ -n "$JS_FILES" ] || [ -n "$SASS_FILES" ];
-    if [ -n "$JS_FILES" ];
-    then
-        npm run test -s;
-        exit 0
-    fi
+if [ -n "$SCSS_STAGED" ];
+then
+    npm run linter:sass -s -- $SCSS_STAGED
+fi
+
+if [ -n "$JS_STAGED" ];
+then
+    npm run test -s
 fi
